### ISSUE TITLE
Don't log ldap credentials

### ISSUE THREAD

**Issue by youngm** [cloudfoundry-incubator/nfsv3driver#4]
I see my ldap credentials in the nfsv3driver logs.  Here is an example:

{"timestamp":"1490822297.744624615","source":"nfs-driver-server","message":"nfs-driver-server.restore-state.state","log_level":1,"data":{"session":"1","state":{"4f2e8cb1-9b27-4ef2-8787-b71e1db3eed69b325045-e089-47df-af57-7b0b227ea8aa":{"Opts":{"password":"somepassword","source":"nfs://nfsv4-test.somedomain.org/test","username":"someuser"},"Name":"4f2e8cb1-9b27-4ef2-8787-b71e1db3eed69b325045-e089-47df-af57-7b0b227ea8aa","Mountpoint":"","MountCount":0}}}}

**Comment by youngm** [comment]
Oops.  I think this is a dup of https://www.pivotaltracker.com/story/show/142358565 sorry bout that.  Feel free to close this issue if you agree.

**Comment by julian-hj** [comment]
Thanks Mike,

We've just delivered the fix for this issue in nfs broker and nfs driver:
https://www.pivotaltracker.com/story/show/142358565

Note however that we still have 2 other open issues that we're working on which will need to be fixed before anyone should consider actually using the feature in a production-type environment:
https://www.pivotaltracker.com/story/show/142810387
https://www.pivotaltracker.com/story/show/142358289

I'm going to leave this issue open in github until we're done addressing those two stories.

**Comment by youngm** [comment]
Thanks @julian-hj If you were interested in my prioritization input, I would consider the logging of credentials orders of magnitude more important to me than the storing of credentials in the file system unencrypted.

Unless I'm missing something I'd almost consider the storing of credentials on the file system unencrypted a non issue.  In a CF deployment we have all kinds of secrets and such on the file system in .json files unencrypted that can be used to do anything, including acquire and unencrypting the volman credentials out of the CC.

My 2 cents.  Thanks!

**Comment by julian-hj** [comment]
This is fixed in nfs-volume-release. It is also fixed in volman, **provided that you are running a Diego version > 1.12.0**. If you are using an earlier version of Diego, and you want to use LDAP integration in nfs-volume-release it is **strongly remommended** that you set your rep log level to error or warn to avoid leaking LDAP credentials into the rep logs.

**Comment by youngm** [comment]
Awesome Thanks @julian-hj
